/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/ai-chatbot`; params?: Router.UnknownInputParams; } | { pathname: `/admin/bookings`; params?: Router.UnknownInputParams; } | { pathname: `/admin/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin/messaging`; params?: Router.UnknownInputParams; } | { pathname: `/therapist/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/booking`; params?: Router.UnknownInputParams; } | { pathname: `/user/bookings`; params?: Router.UnknownInputParams; } | { pathname: `/user/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/user/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/messaging`; params?: Router.UnknownInputParams; } | { pathname: `/user/services`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/ai-chatbot`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/bookings`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/messaging`; params?: Router.UnknownOutputParams; } | { pathname: `/therapist/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/user/booking`; params?: Router.UnknownOutputParams; } | { pathname: `/user/bookings`; params?: Router.UnknownOutputParams; } | { pathname: `/user/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `/user/chatbot`; params?: Router.UnknownOutputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/user/messaging`; params?: Router.UnknownOutputParams; } | { pathname: `/user/services`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/ai-chatbot${`?${string}` | `#${string}` | ''}` | `/admin/bookings${`?${string}` | `#${string}` | ''}` | `/admin/calendar${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/admin/messaging${`?${string}` | `#${string}` | ''}` | `/therapist/dashboard${`?${string}` | `#${string}` | ''}` | `/user/booking${`?${string}` | `#${string}` | ''}` | `/user/bookings${`?${string}` | `#${string}` | ''}` | `/user/calendar${`?${string}` | `#${string}` | ''}` | `/user/chatbot${`?${string}` | `#${string}` | ''}` | `/user/dashboard${`?${string}` | `#${string}` | ''}` | `/user/messaging${`?${string}` | `#${string}` | ''}` | `/user/services${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/ai-chatbot`; params?: Router.UnknownInputParams; } | { pathname: `/admin/bookings`; params?: Router.UnknownInputParams; } | { pathname: `/admin/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin/messaging`; params?: Router.UnknownInputParams; } | { pathname: `/therapist/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/booking`; params?: Router.UnknownInputParams; } | { pathname: `/user/bookings`; params?: Router.UnknownInputParams; } | { pathname: `/user/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/user/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/messaging`; params?: Router.UnknownInputParams; } | { pathname: `/user/services`; params?: Router.UnknownInputParams; };
    }
  }
}
